# Generated by Django 2.0.3 on 2020-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField()),
            ],
        ),
    ]
